export const LOGIN = 'LOGIN';
export const REQUEST_CURRENCIES_INFO = 'REQUEST_CURRENCIES_INFO';
export const RECEIVE_CURRENCIES_SUCCESS = 'RECEIVE_CURRENCIES_SUCCESS';
export const RECEIVE_CURRENCIES_FAILURE = 'RECEIVE_CURRENCIES_FAILURE';
